name: ip_tv
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  get: 4.6.6
  get_cli: ^1.8.1
  get_storage: ^2.1.1
  http: ^1.2.1
  iconsax: ^0.0.8
  intl: ^0.19.0
  logger: ^2.3.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/image.png
    - assets/images/iptv logo.png
    - assets/images/bg2.png
    - assets/images/sample.png
    - assets/images/vpn.png
    - assets/images/setting.png
    - assets/images/back_button.png
    - assets/images/bg3.png
    - assets/images/bg_icons.png
    - assets/images/speedometer.png
    - assets/icons/gs.png
    - assets/icons/stream.png
    - assets/icons/clock.png
    - assets/icons/parental-control.png
    - assets/icons/automation.png
    - assets/icons/epg.png
    - assets/icons/themes.png
    - assets/icons/player.png
    - assets/icons/speed.png

